AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'vendor/**/*'
    - 'Gemfile'
Layout/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/InclusiveLanguage:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - lib/**/*
    - 'spec/**/*'
