AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'vendor/**/*'
    - 'Gemfile'
Layout/LineLength:
  Max: 200
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Naming/InclusiveLanguage:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - lib/**/*
    - 'spec/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
