version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          PG_HOST: 127.0.0.1
          PGUSER: ads
      - image: circleci/postgres:12.9
        environment:
          POSTGRES_DB: ads_test
          POSTGRES_USER: ads
          POSTGRES_PASSWORD: 2905
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler:1.17.3
      - restore_cache:
          name: Restore bundle cache
          key: ads-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          name: Store bundle cache
          key: ads-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rubocop
      - run: bundle exec rake db:setup
      - run: bundle exec rake
